### ISSUE TITLE
cant get the token to input into the bot

### ISSUE THREAD

**Issue by themomospinyo** [LucaArgentieri/Shoe-Discord-Bot#15]
hello! im getting a token invalid error when trying to run the bot. how to i do that .env file, what should i name it?
![Screenshot 2022-09-15 120601](https://user-images.githubusercontent.com/66923444/190453087-9b3d4920-3181-456f-93eb-adcd2e945e38.png)

**Comment by LucaArgentieri** [comment]
Hey!
Create in the root a .env file (like [this](https://github.com/LucaArgentieri/Shoe-Discord-Bot/blob/master/.env.example))

`BOT_TOKEN_KEY=Insert here your discord bot token
`

And you are ready to go! 😄

**Comment by themomospinyo** [comment]
does it need to be a specific name? i did it as (token).env
should i do root.env or something else

**Comment by themomospinyo** [comment]
not good with coding, this is prob an easy thing to do but i have no clue

**Comment by themomospinyo** [comment]
![image](https://user-images.githubusercontent.com/66923444/190495208-f753546d-3634-49ef-80dd-67244be05030.png)

**Comment by themomospinyo** [comment]
![image](https://user-images.githubusercontent.com/66923444/190495389-42a66ae5-ba58-43a6-b906-5d12454888c5.png)

**Comment by LucaArgentieri** [comment]
Once you created the .env and added the variable you have to restart the server

**Comment by themomospinyo** [comment]
i found it i put the client token instead of the bot token 
my bad

**Comment by themomospinyo** [comment]
![image](https://user-images.githubusercontent.com/66923444/190496173-0f6488ce-3710-474c-8591-76160c533228.png)

**Comment by themomospinyo** [comment]
and its not loading anything.....
