### ISSUE TITLE
Contest/ command does not get scraped

### ISSUE THREAD

**Issue by Takshoe** [LucaArgentieri/Shoe-Discord-Bot#20]
Bot is online, but there is not content getting recognised by Bot

**Comment by LucaArgentieri** [comment]
Have you tried using some commands like $help?
What's the response from the bot?

**Comment by Takshoe** [comment]
Hey, I found the issue.

You maybe want to add this to your setup Guide:
- You need to enable "MESSAGE CONTENT INTENT" on the Discord Bot SETUP Page.

Great work guys!

PS: Maybe you wanna add product Page Links for each Resell Site for each shoe on the embeded Webhook :)

**Comment by LucaArgentieri** [comment]
> Hey, I found the issue.
> 
> You maybe want to add this to your setup Guide:
> 
> * You need to enable "MESSAGE CONTENT INTENT" on the Discord Bot SETUP Page.
> 
> Great work guys!
> 
> PS: Maybe you wanna add product Page Links for each Resell Site for each shoe on the embeded Webhook :)

I'll fix it right away, thanks for your contribution.
I really appreciate that.

**Comment by LucaArgentieri** [comment]
Updated doc with [Message Content Intent](https://github.com/LucaArgentieri/Shoe-Discord-Bot/blob/master/README.md#now-move-in-bot-tab-and-tick)

Thanks @Takshoe
